<a href="https://colab.research.google.com/github/siddharth0517/Predicting-Power-Plant-Energy-Output/blob/main/Predicting_Power_Plant_Energy_Output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Predicting Power Plant Energy Output Using Environmental Factors: A Regression Analysis

**1. Importing required Libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**2. Importing Dataset**

In [5]:
Dataset = pd.read_csv('Data.csv')
X = Dataset.iloc[:,:-1].values
y = Dataset.iloc[:,-1].values
y = y.reshape(len(y),1)

**3. Splitting The Dataset into Train and Test**

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

**4. Feature Scaling**

In [33]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)



**5. Building all The Regression Models**

**. Linear Regression**

In [9]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

**. Support vector Regression**

In [11]:
from sklearn import svm
svr = svm.SVR()
svr.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

**. Decision Tree Regression**

In [12]:
from sklearn import tree
dtr = tree.DecisionTreeRegressor(random_state=0)
dtr.fit(X_train,y_train)

DecisionTreeRegressor(random_state=0)

**. Random Forest Regression**

In [14]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_estimators=15,random_state=0)
rfr.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(n_estimators=15, random_state=0)

**6. Predicting our Model**

**. Linear Regression**

In [16]:
y_pred_lr = sc_y.inverse_transform(lr.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_lr.reshape(len(y_pred_lr),1), y_test.reshape(len(y_test),1)),1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


**. SVM**

In [21]:
y_pred_svm = sc_y.inverse_transform(svr.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_svm.reshape(len(y_pred_svm),1), y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


**.Decision Tree Regrssion**

In [22]:
y_pred_dtr = sc_y.inverse_transform(dtr.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_dtr.reshape(len(y_pred_dtr),1), y_test.reshape(len(y_test),1)),1))

[[431.37 431.23]
 [459.59 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.55 463.28]]


**. RFR**

In [23]:
y_pred_rfr = sc_y.inverse_transform(rfr.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_rfr.reshape(len(y_pred_rfr),1), y_test.reshape(len(y_test),1)),1))

[[433.49 431.23]
 [457.06 460.01]
 [463.61 461.14]
 ...
 [468.84 473.26]
 [439.35 438.  ]
 [460.31 463.28]]


**7. Model Evaluation**

In [34]:
from sklearn.metrics import r2_score
print("Linear Regression R2 Score: ",r2_score(y_test,y_pred_lr))
print("SVM R2 Score: ",r2_score(y_test,y_pred_svm))
print("Decision Tree Regression R2 Score: ",r2_score(y_test,y_pred_dtr))
print("Random Forest Regression R2 Score: ",r2_score(y_test,y_pred_rfr))

Linear Regression R2 Score:  0.9325315554761303
SVM R2 Score:  0.9480784049986258
Decision Tree Regression R2 Score:  0.9245677025270336
Random Forest Regression R2 Score:  0.9630391220921899


**Exporting Result For Visualization**

In [36]:
comparison_df = pd.DataFrame({
    'Predicted_PE_LR': y_pred_lr.flatten(),
    'Predicted_PE_SVR': y_pred_svm.flatten(),
    'Predicted_PE_DTR': y_pred_dtr.flatten(),
    'Predicted_PE_RFR': y_pred_rfr.flatten(),
    'Actual_PE': y_test.flatten()
})

In [37]:
comparison_df.to_csv('Power_plant_energy_output_predictions.csv', index=False)